// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaleMasterApi.Data;

#nullable disable

namespace SaleMasterApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260222232650_AddCaracteristica")]
    partial class AddCaracteristica
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SaleMasterApi.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("SaleMasterApi.Models.Produto", b =>
                {
                    b.OwnsOne("SaleMasterApi.Models.Caracteristica", "Caracteristica", b1 =>
                        {
                            b1.Property<int>("ProdutoId")
                                .HasColumnType("int");

                            b1.Property<string>("Cor")
                                .HasColumnType("longtext");

                            b1.Property<string>("Marca")
                                .HasColumnType("longtext");

                            b1.Property<string>("Material")
                                .HasColumnType("longtext");

                            b1.Property<string>("Tamanho")
                                .HasColumnType("longtext");

                            b1.HasKey("ProdutoId");

                            b1.ToTable("Produtos");

                            b1.WithOwner()
                                .HasForeignKey("ProdutoId");
                        });

                    b.Navigation("Caracteristica");
                });
#pragma warning restore 612, 618
        }
    }
}
